FROM ubuntu:20.04 

ARG DEBIAN_FRONTEND=noninteractive

# Install the required packages
RUN apt-get update \
    && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get install -y python3 pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/OpenDriveLab/OpenLane-V2.git /OpenLaneV2\
    && cd /OpenLaneV2 \
    && pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ \
    && pip install --no-cache-dir -e .

WORKDIR /OpenLaneV2